### ISSUE TITLE
helm-selection background not inherited

### ISSUE THREAD

**Issue by ghost** [avkoval/avk-emacs-themes#4]
Hi! First of all, awesome theme! the daylight variation is one of my favourites <3, but I'm having a little problem with it, for some reason I need to explicitly add the background to `helm-selection` face: 
```elisp
`(helm-selection ((t (:inherit hl-line :background "SlateGray1"))))
```
otherwise the background is white and it's very hard to know which option is selected, Do you have that same problem?

**Comment by avkoval** [comment]
Hi,

At first, sorry for this serious delay in addressing this topic, but it seems I missed the notification due to a lot of things going on my github account.

2nd I don't have this kind of problem, but I don't mind adding your fix if it helps you. Just added.

Please tell me @anler if this fixes your problem!

WBR,
   Alex

**Comment by ghost** [comment]
Hi @avkoval not sure why but I can't find the package in Melpa :(

**Comment by avkoval** [comment]
Hi @anler 
Fixed the problem above (was a problem due to missing LICENSE, I've added it)

**Comment by ghost** [comment]
Thanks @avkoval and I checked again and know it looks ok, probably was some stale setting in my `custom.el` file or something. Thanks!
